// Enhanced course data with properties for tab filtering
export interface EnhancedCourseData {
  id: string,
  title: string,
  popularity: number 
  dateAdded: string,
  description: string,
  level: "Beginner" | "Intermediate" | "Advanced",
  durationHours: number,
  studentsCount: number,
  rating: number,
  trendingScore: number,
  imageUrl: string,
  instructor?: string,  // Added as optional
  duration?: string,    // Added as optional
  features?: string[]   // Added as optional
}

// This will contain Centralized course data that can be imported by both the home page and courses page
// This is the hard-coded course data in place of when we fetch data in the future
export const allCourses: EnhancedCourseData[] = [
  {
    id: "blockchain-fundamentals",
    title: "Fundamentals of Blockchain Technology",
    description: "Learn the core concepts of blockchain, distributed ledgers, and consensus mechanisms.",
    level: "Beginner" as const,
    durationHours: 6,
    studentsCount: 1245,
    rating: 4.8,
    popularity: 95,
    dateAdded: "2023-10-15",
    trendingScore: 75,
    imageUrl: "/images/courses/blockchain-fundamentals.jpg",
  },
  {
    id: "stellar-smart-contract",
    title: "Stellar Smart Contract Development",
    description: "Master the art of building secure and efficient smart contracts on the Stellar network.",
    level: "Intermediate" as const,
    durationHours: 8,
    studentsCount: 876,
    rating: 4.9,
    popularity: 85,
    dateAdded: "2023-11-20",
    trendingScore: 90,
    imageUrl: "/images/courses/stellar-smart-contract.jpg",
  },
  {
    id: "defi-stellar",
    title: "Decentralized Finance (DeFi) on Stellar",
    description: "Explore the world of DeFi and learn how to build financial applications on Stellar.",
    level: "Advanced" as const,
    durationHours: 10,
    studentsCount: 654,
    rating: 4.7,
    popularity: 80,
    dateAdded: "2023-09-05",
    trendingScore: 85,
    imageUrl: "/images/courses/defi-stellar.jpg",
  },
  {
    id: "blockchain-security",
    title: "Blockchain Security Fundamentals",
    description: "Learn essential security practices for blockchain applications and smart contracts.",
    level: "Intermediate" as const,
    durationHours: 7,
    studentsCount: 932,
    rating: 4.6,
    popularity: 88,
    dateAdded: "2023-08-12",
    trendingScore: 70,
    imageUrl: "/images/courses/blockchain-security.jpg",
  },
  {
    id: "crypto-trading",
    title: "Cryptocurrency Trading Strategies",
    description: "Master the fundamentals of cryptocurrency trading and portfolio management.",
    level: "Beginner" as const,
    durationHours: 5,
    studentsCount: 1876,
    rating: 4.5,
    popularity: 98,
    dateAdded: "2023-07-25",
    trendingScore: 65,
    imageUrl: "/images/courses/crypto-trading.jpg",
  },
  {
    id: "nft-development",
    title: "NFT Development and Marketplace",
    description: "Build your own NFT collection and marketplace on the Stellar blockchain.",
    level: "Advanced" as const,
    durationHours: 12,
    studentsCount: 543,
    rating: 4.9,
    popularity: 75,
    dateAdded: "2024-01-10",
    trendingScore: 95,
    imageUrl: "/images/courses/nft-development.jpg",
  },
  {
    id: "blockchain-governance",
    title: "Blockchain Governance Models",
    description: "Explore different governance models for decentralized networks and DAOs.",
    level: "Advanced" as const,
    durationHours: 9,
    studentsCount: 421,
    rating: 4.8,
    popularity: 70,
    dateAdded: "2024-02-05",
    trendingScore: 80,
    imageUrl: "/images/courses/blockchain-governance.jpg",
  },
]
