import { Course } from '@/types/lesson';

export const mockCourses: Record<string, Course> = {
  'blockchain-fundamentals': {
    id: 'blockchain-fundamentals',
    title: 'Fundamentals of Blockchain Technology',
    description: 'Learn the core concepts of blockchain, distributed ledgers, and consensus mechanisms.',
    instructor: 'Dr. Sarah Chen',
    totalLessons: 8,
    completedLessons: 0,
    progress: 0,
    lessons: [
    {
      id: 'lesson-1',
      title: 'Introduction to Blockchain',
      description: 'Understanding the basics of blockchain technology and its revolutionary impact.',
      videoUrl: '/videos/demo-video.mp4',
      duration: 480, // 8 minutes
      order: 1,
      type: 'video',
      isCompleted: false,
      isLocked: false,
    },
    {
      id: 'lesson-2',
      title: 'Cryptographic Foundations',
      description: 'Explore the cryptographic principles that secure blockchain networks.',
      videoUrl: '/videos/demo-video.mp4',
      duration: 600, // 10 minutes
      order: 2,
      type: 'video',
      isCompleted: false,
      isLocked: true,
    },
    {
      id: 'lesson-3',
      title: 'Distributed Ledger Technology',
      description: 'Deep dive into how distributed ledgers work and their advantages.',
      videoUrl: '/videos/demo-video.mp4',
      duration: 720, // 12 minutes
      order: 3,
      type: 'video',
      isCompleted: false,
      isLocked: true,
    },
    {
      id: 'lesson-4',
      title: 'Consensus Mechanisms',
      description: 'Learn about Proof of Work, Proof of Stake, and other consensus algorithms.',
      videoUrl: '/videos/demo-video.mp4',
      duration: 540, // 9 minutes
      order: 4,
      type: 'video',
      isCompleted: false,
      isLocked: true,
    },
    {
      id: 'lesson-5',
      title: 'Smart Contracts Basics',
      description: 'Introduction to smart contracts and their role in blockchain ecosystems.',
      videoUrl: '/videos/demo-video.mp4',
      duration: 660, // 11 minutes
      order: 5,
      type: 'video',
      isCompleted: false,
      isLocked: true,
    },
    {
      id: 'lesson-6',
      title: 'Blockchain Networks',
      description: 'Understanding public, private, and consortium blockchain networks.',
      videoUrl: '/videos/demo-video.mp4',
      duration: 480, // 8 minutes
      order: 6,
      type: 'video',
      isCompleted: false,
      isLocked: true,
    },
    {
      id: 'lesson-7',
      title: 'Security and Vulnerabilities',
      description: 'Common security issues in blockchain and how to mitigate them.',
      videoUrl: '/videos/demo-video.mp4',
      duration: 600, // 10 minutes
      order: 7,
      type: 'video',
      isCompleted: false,
      isLocked: true,
    },
    {
      id: 'lesson-8',
      title: 'Future of Blockchain',
      description: 'Exploring emerging trends and the future potential of blockchain technology.',
      videoUrl: '/videos/demo-video.mp4',
      duration: 540, // 9 minutes
      order: 8,
      type: 'video',
      isCompleted: false,
      isLocked: true,
    },
  ],
  },
  'stellar-smart-contracts': {
    id: 'stellar-smart-contracts',
    title: 'Stellar Smart Contracts Development',
    description: 'Master smart contract development on the Stellar blockchain using Soroban.',
    instructor: 'Miguel Rodriguez',
    totalLessons: 6,
    completedLessons: 0,
    progress: 0,
    lessons: [
      {
        id: 'lesson-1',
        title: 'Introduction to Stellar',
        description: 'Overview of the Stellar network and its unique features.',
        videoUrl: '/videos/demo-video.mp4',
        duration: 420,
        order: 1,
        type: 'video',
        isCompleted: false,
        isLocked: false,
      },
      {
        id: 'lesson-2',
        title: 'Soroban Basics',
        description: 'Getting started with Soroban smart contracts.',
        videoUrl: '/videos/demo-video.mp4',
        duration: 540,
        order: 2,
        type: 'video',
        isCompleted: false,
        isLocked: true,
      },
      {
        id: 'lesson-3',
        title: 'Writing Your First Contract',
        description: 'Build and deploy your first Soroban smart contract.',
        videoUrl: '/videos/demo-video.mp4',
        duration: 720,
        order: 3,
        type: 'video',
        isCompleted: false,
        isLocked: true,
      },
      {
        id: 'lesson-4',
        title: 'Contract Testing',
        description: 'Learn how to test and debug Soroban contracts.',
        videoUrl: '/videos/demo-video.mp4',
        duration: 600,
        order: 4,
        type: 'video',
        isCompleted: false,
        isLocked: true,
      },
      {
        id: 'lesson-5',
        title: 'Advanced Contract Patterns',
        description: 'Explore advanced patterns and best practices.',
        videoUrl: '/videos/demo-video.mp4',
        duration: 660,
        order: 5,
        type: 'video',
        isCompleted: false,
        isLocked: true,
      },
      {
        id: 'lesson-6',
        title: 'Production Deployment',
        description: 'Deploy and manage contracts in production.',
        videoUrl: '/videos/demo-video.mp4',
        duration: 540,
        order: 6,
        type: 'video',
        isCompleted: false,
        isLocked: true,
      },
    ],
  },
  'defi-fundamentals': {
    id: 'defi-fundamentals',
    title: 'DeFi Fundamentals on Stellar',
    description: 'Understand decentralized finance concepts and build DeFi applications on Stellar.',
    instructor: 'Aisha Patel',
    totalLessons: 7,
    completedLessons: 0,
    progress: 0,
    lessons: [
      {
        id: 'lesson-1',
        title: 'What is DeFi?',
        description: 'Introduction to decentralized finance and its impact.',
        videoUrl: '/videos/demo-video.mp4',
        duration: 360,
        order: 1,
        type: 'video',
        isCompleted: false,
        isLocked: false,
      },
      {
        id: 'lesson-2',
        title: 'Liquidity Pools',
        description: 'Understanding liquidity pools and automated market makers.',
        videoUrl: '/videos/demo-video.mp4',
        duration: 480,
        order: 2,
        type: 'video',
        isCompleted: false,
        isLocked: true,
      },
      {
        id: 'lesson-3',
        title: 'Stellar DEX',
        description: 'Exploring the Stellar decentralized exchange.',
        videoUrl: '/videos/demo-video.mp4',
        duration: 540,
        order: 3,
        type: 'video',
        isCompleted: false,
        isLocked: true,
      },
      {
        id: 'lesson-4',
        title: 'Lending Protocols',
        description: 'Building lending and borrowing protocols.',
        videoUrl: '/videos/demo-video.mp4',
        duration: 600,
        order: 4,
        type: 'video',
        isCompleted: false,
        isLocked: true,
      },
      {
        id: 'lesson-5',
        title: 'Yield Farming',
        description: 'Understanding yield farming strategies.',
        videoUrl: '/videos/demo-video.mp4',
        duration: 420,
        order: 5,
        type: 'video',
        isCompleted: false,
        isLocked: true,
      },
      {
        id: 'lesson-6',
        title: 'Risk Management',
        description: 'Managing risks in DeFi applications.',
        videoUrl: '/videos/demo-video.mp4',
        duration: 480,
        order: 6,
        type: 'video',
        isCompleted: false,
        isLocked: true,
      },
      {
        id: 'lesson-7',
        title: 'Building a DeFi App',
        description: 'Create your own DeFi application on Stellar.',
        videoUrl: '/videos/demo-video.mp4',
        duration: 720,
        order: 7,
        type: 'video',
        isCompleted: false,
        isLocked: true,
      },
    ],
  },
  'nft-development': {
    id: 'nft-development',
    title: 'NFT Development & Marketplace',
    description: 'Learn to create, mint, and trade NFTs on blockchain platforms.',
    instructor: 'Dr. Sarah Chen',
    totalLessons: 5,
    completedLessons: 0,
    progress: 0,
    lessons: [
      {
        id: 'lesson-1',
        title: 'NFT Fundamentals',
        description: 'Understanding non-fungible tokens and their use cases.',
        videoUrl: '/videos/demo-video.mp4',
        duration: 420,
        order: 1,
        type: 'video',
        isCompleted: false,
        isLocked: false,
      },
      {
        id: 'lesson-2',
        title: 'Token Standards',
        description: 'Exploring ERC-721, ERC-1155, and other NFT standards.',
        videoUrl: '/videos/demo-video.mp4',
        duration: 540,
        order: 2,
        type: 'video',
        isCompleted: false,
        isLocked: true,
      },
      {
        id: 'lesson-3',
        title: 'Minting NFTs',
        description: 'Create and mint your first NFT collection.',
        videoUrl: '/videos/demo-video.mp4',
        duration: 600,
        order: 3,
        type: 'video',
        isCompleted: false,
        isLocked: true,
      },
      {
        id: 'lesson-4',
        title: 'NFT Marketplace',
        description: 'Building an NFT marketplace from scratch.',
        videoUrl: '/videos/demo-video.mp4',
        duration: 720,
        order: 4,
        type: 'video',
        isCompleted: false,
        isLocked: true,
      },
      {
        id: 'lesson-5',
        title: 'Royalties & Licensing',
        description: 'Implementing royalties and managing IP rights.',
        videoUrl: '/videos/demo-video.mp4',
        duration: 480,
        order: 5,
        type: 'video',
        isCompleted: false,
        isLocked: true,
      },
    ],
  },
};

// Helper function to get a course by ID
export const getCourseById = (courseId: string): Course | undefined => {
  return mockCourses[courseId];
};

// Helper function to get all courses
export const getAllCourses = (): Course[] => {
  return Object.values(mockCourses);
};

// Legacy export for backward compatibility
export const mockCourseData = mockCourses['blockchain-fundamentals'];