export const mockQuestions = [
  {
    id: 1,
    question: 'How many days are there in a week?',
    options: ['5', '6', '7', '8'],
    correctAnswer: 2,
  },
  {
    id: 2,
    question: 'Which of these is a healthy habit?',
    options: [
      'Sleeping 3 hours daily',
      'Drinking enough water',
      'Skipping meals regularly',
      'Avoiding exercise',
    ],
    correctAnswer: 1,
  },
  {
    id: 3,
    question: 'What should you do before crossing the road?',
    options: [
      'Run quickly',
      'Look left and right',
      'Close your eyes',
      'Use your phone',
    ],
    correctAnswer: 1,
  },
  {
    id: 4,
    question: 'Which of these helps you save money?',
    options: [
      'Impulse buying',
      'Budgeting',
      'Ignoring expenses',
      'Borrowing unnecessarily',
    ],
    correctAnswer: 1,
  },
  {
    id: 5,
    question: 'Which emotion is considered positive?',
    options: ['Anger', 'Jealousy', 'Gratitude', 'Hatred'],
    correctAnswer: 2,
  },
  {
    id: 6,
    question: 'How many minutes are in one hour?',
    options: ['30', '45', '60', '90'],
    correctAnswer: 2,
  },
  {
    id: 7,
    question: 'Which of these is important for good communication?',
    options: [
      'Interrupting others',
      'Listening carefully',
      'Shouting',
      'Ignoring feedback',
    ],
    correctAnswer: 1,
  },
  {
    id: 8,
    question: 'What is the boiling point of water at sea level?',
    options: ['50°C', '100°C', '150°C', '200°C'],
    correctAnswer: 1,
  },
  {
    id: 9,
    question: 'Which of these is a renewable resource?',
    options: ['Coal', 'Petrol', 'Solar energy', 'Diesel'],
    correctAnswer: 2,
  },
  {
    id: 10,
    question: 'Which meal is often called the most important of the day?',
    options: ['Lunch', 'Dinner', 'Snack', 'Breakfast'],
    correctAnswer: 3,
  },
  {
    id: 11,
    question: 'Which of these is good time management?',
    options: [
      'Procrastinating',
      'Planning your tasks',
      'Ignoring deadlines',
      'Wasting time',
    ],
    correctAnswer: 1,
  },
  {
    id: 12,
    question: 'What should you do if you make a mistake?',
    options: [
      'Blame others',
      'Ignore it',
      'Accept and learn from it',
      'Hide it',
    ],
    correctAnswer: 2,
  },
  {
    id: 13,
    question: 'How many continents are there?',
    options: ['5', '6', '7', '8'],
    correctAnswer: 2,
  },
  {
    id: 14,
    question: 'Which of these improves mental health?',
    options: [
      'Constant stress',
      'Regular exercise',
      'Isolation',
      'Negative thinking',
    ],
    correctAnswer: 1,
  },
  {
    id: 15,
    question: 'What is a good way to resolve conflict?',
    options: [
      'Argue loudly',
      'Avoid communication',
      'Calm discussion',
      'Ignore the issue',
    ],
    correctAnswer: 2,
  },
  {
    id: 16,
    question: 'Which of these is a basic need?',
    options: ['Luxury car', 'Designer clothes', 'Food', 'Expensive phone'],
    correctAnswer: 2,
  },
  {
    id: 17,
    question: 'How many months are in a year?',
    options: ['10', '11', '12', '13'],
    correctAnswer: 2,
  },
  {
    id: 18,
    question: 'Which of these is an example of kindness?',
    options: [
      'Helping someone in need',
      'Mocking others',
      'Spreading rumors',
      'Ignoring problems',
    ],
    correctAnswer: 0,
  },
  {
    id: 19,
    question: 'What is the primary purpose of education?',
    options: [
      'To compete with others',
      'To gain knowledge and skills',
      'To avoid responsibility',
      'To show off',
    ],
    correctAnswer: 1,
  },
  {
    id: 20,
    question: 'Which of these helps maintain physical fitness?',
    options: [
      'Sedentary lifestyle',
      'Regular exercise',
      'Skipping meals',
      'Excess junk food',
    ],
    correctAnswer: 1,
  },
];
