import type { Metadata } from 'next';
import { Inter, Source_Code_Pro } from 'next/font/google';
import './globals.css';
import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import CookieBanner from '@/components/CookieBanner';
import Analytics from '@/components/Analytics';
import { Toaster } from 'sonner';
import { Providers } from '@/lib/providers';
import EnvironmentValidator from '@/components/EnvironmentValidator';
import { initializeServerEnvironment } from '@/lib/env-server';
import StyledComponentsRegistry from '@/lib/registry';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

const sourceCodePro = Source_Code_Pro({
  variable: '--font-source-code-pro',
  subsets: ['latin'],
});

// Determine the base URL based on environment
const getBaseUrl = () => {
  if (process.env.NEXT_PUBLIC_VERCEL_ENV === 'production') {
    return 'https://strellerminds.com';
  }
  if (process.env.NEXT_PUBLIC_VERCEL_URL) {
    return `https://${process.env.NEXT_PUBLIC_VERCEL_URL}`;
  }
  return 'http://localhost:3000';
};

const baseUrl = getBaseUrl();

export const metadata: Metadata = {
  metadataBase: new URL(baseUrl),

  title: {
    default: 'StrellerMinds - Blockchain Education Platform',
    template: '%s | StrellerMinds',
  },

  description:
    'Empowering minds through cutting-edge blockchain education. Learn DeFi, Smart Contracts, and blockchain development with expert-led courses.',

  keywords: [
    'blockchain',
    'education',
    'DeFi',
    'smart contracts',
    'cryptocurrency',
    'web3',
    'learning platform',
    'blockchain courses',
    'crypto education',
    'decentralized finance',
  ],

  authors: [{ name: 'StrellerMinds Team' }],
  creator: 'StrellerMinds',
  publisher: 'StrellerMinds',

  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },

  // Canonical URL configuration
  alternates: {
    canonical: '/',
    languages: {
      'en-US': '/en-US',
    },
  },

  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: baseUrl,
    siteName: 'StrellerMinds',
    title: 'StrellerMinds - Blockchain Education Platform',
    description:
      'Empowering minds through cutting-edge blockchain education. Learn DeFi, Smart Contracts, and blockchain development with expert-led courses.',
    images: [
      {
        url: '/opengraph-image.png', // This is auto-generated by your opengraph-image.tsx
        width: 1200,
        height: 630,
        alt: 'StrellerMinds - Blockchain Education Platform',
      },
    ],
  },

  twitter: {
    card: 'summary_large_image',
    title: 'StrellerMinds - Blockchain Education Platform',
    description:
      'Empowering minds through cutting-edge blockchain education. Learn DeFi, Smart Contracts, and blockchain development with expert-led courses.',
    creator: '@strellerminds',
    images: ['/opengraph-image.png'], // This is auto-generated
  },

  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },

  verification: {
    google: 'your-google-verification-code',
  },
};

// Initialize server environment validation
initializeServerEnvironment();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} ${sourceCodePro.variable}`}>
        <EnvironmentValidator />
        <Providers>
          <StyledComponentsRegistry>
            {/* Accessibility Skip Link */}
            <a
              href="#main-content"
              className="sr-only focus:not-sr-only focus:absolute focus:top-2 focus:left-16 focus:bg-[#5c0f49] focus:text-white focus:p-4 focus:outline-none focus:z-100"
            >
              Skip to content
            </a>

            <Navbar />
            <main id="main-content">{children}</main>
            <Footer />
            <Toaster position="top-right" />

            {/* Privacy-compliant Analytics */}
            <Analytics />

            {/* Cookie Consent Banner */}
            <CookieBanner />
          </StyledComponentsRegistry>
        </Providers>
      </body>
    </html>
  );
}
